asf_product_homepage:
    path: /
    defaults: { _controller: "ASFProductBundle:Default:index" }
    
af_product_default:
    resource: "@ASFProductBundle/Resources/config/routing/default.yml"
    
asf_product_brand:
    prefix: /brand
    resource: "@ASFProductBundle/Resources/config/routing/brand.yml"

asf_product_ajax:
    resource: "@ASFProductBundle/Resources/config/routing/ajax_request.yml"