asf_product_brand_list:
    path: /list
    defaults: { _controller: "ASFProductBundle:Brand:list" }
    
asf_product_brand_edit:
    path: /edit/{id}
    defaults: { _controller: "ASFProductBundle:Brand:edit" }
    
asf_product_brand_add:
    path: /add
    defaults: { _controller: "ASFProductBundle:Brand:edit" }
    
asf_product_brand_delete:
    path: /delete/{id}
    defaults: { _controller: "ASFProductBundle:Brand:delete" }
    
asf_product_brand_ajax_request:
    path: /ajax/request
    defaults: { _controller: "ASFProductBundle:Brand:ajaxRequest" }
    options:
        expose: true