asf_product_homepage:
    path: /
    defaults: { _controller: "ASFProductBundle:Default:index" }
    
asf_user_ajax_request_product_by_name:
    path: /ajax/request/search/product/by/name
    defaults: { _controller: "ASFProductBundle:AjaxRequest:searchProductByName" }
    options:
        expose: true
        
asf_user_ajax_request_category_by_name:
    path: /ajax/request/search/category/by/name
    defaults: { _controller: "ASFProductBundle:AjaxRequest:searchCategoryByName" }
    options:
        expose: true   
        
asf_user_ajax_request_brand_by_name:
    path: /ajax/request/search/brand/by/name
    defaults: { _controller: "ASFProductBundle:AjaxRequest:searchBrandByName" }
    options:
        expose: true        